### ISSUE TITLE
Upsert is not working on 2.0.0-alpha 

### ISSUE THREAD

**Issue by vigneshtvp** [confluentinc/kafka-connect-bigquery#103]
Hi @C0urante,

Upsert is not happening  on 2.0.0-alpha, Please do let us know whether this is supported in this version.

If so, i am using below config for bigquery sink connector, please let us know what makes wrong on this config properties.

autoUpdateSchemas=true
sanitizeTopics=true
autoCreateTables=true
tasks.max=1
topics=kafkaconnectinformixv6
allowSchemaUnionization=true
upsertEnabled=true
project=****
maxWriteSize=10000
defaultDataset=****
value.converter.schema.registry.url=*****
schema.registry.url=***
kafkaKeyFieldName=rcv_unit_id
allowNewBigQueryFields=true
keyfile=***
schemaRetriever=com.wepay.kafka.connect.bigquery.retrieve.IdentitySchemaRetriever
value.converter=io.confluent.connect.avro.AvroConverter
key.converter=io.confluent.connect.avro.AvroConverter
tableWriteWait=500
key.converter.schema.registry.url=****
intermediateTableSuffix=_tmp
bufferSize=100000

Also in Bigquery table, my kafka key message is always creating column name as "rcv_unit_id.rcv_unit_id", is there any way to change the name from  "rcv_unit_id.rcv_unit_id" to " "rcv_unit_id".

**Comment by C0urante** [comment]
Hi @vigneshtvp--I'm not aware of any 2.0.0-alpha release of the connector; can you try with an official release for version 2.0.0+? And if that doesn't work either, can you provide specific details on what appears to be going wrong?

In order to answer your question about the key column, it's difficult to say for sure without info on what the actual message keys look like, but I suspect the answer is "no" for the time being.

**Comment by C0urante** [comment]
Closing due to lack of response; @vigneshtvp feel free to reopen if you're still seeing this issue and are able to get the requested information.
