### ISSUE TITLE
Could you please add kafka record timestamp from kafka message as well as system time ? 

### ISSUE THREAD

**Issue by barisAtmn** [confluentinc/kafka-connect-bigquery#113]
public static Map<String, Object> buildKafkaDataRecord(SinkRecord kafkaConnectRecord) {
        HashMap<String, Object> kafkaData = new HashMap<>();
        kafkaData.put(KAFKA_DATA_TOPIC_FIELD_NAME, kafkaConnectRecord.topic());
        kafkaData.put(KAFKA_DATA_PARTITION_FIELD_NAME, kafkaConnectRecord.kafkaPartition());
        kafkaData.put(KAFKA_DATA_OFFSET_FIELD_NAME, kafkaConnectRecord.kafkaOffset());
        kafkaData.put(KAFKA_DATA_INSERT_TIME_FIELD_NAME, System.currentTimeMillis() / 1000.0);
        return kafkaData;
    }

**Comment by C0urante** [comment]
This can be accomplished via the [InsertField](https://docs.confluent.io/platform/current/connect/transforms/insertfield.html) SMT with the `timestamp.field` property. We could modify the connector to accomplish this too but since this logic is fairly general and could apply to many different sink connectors, it's better to implement as an SMT that can be written once and used anywhere.
