### ISSUE TITLE
Topicname as tablename but kafka meta data does not show originating topic names in 2.0 

### ISSUE THREAD

**Issue by albantsui** [confluentinc/kafka-connect-bigquery#166]
After upgrading according to
https://docs.confluent.io/kafka-connect-bigquery/current/overview.html#upgrading-to-2-0-0
we use RegexRouter, following the example, in order to map the topic name to table name needed, as we cannot use `topicsToTables` anymore.
We have various topics going into the same table named "sms_unified_outgoing"
That part is working fine, but we end up in the KAFKA meta data included in a row having topic's name being always the "table name" now, and we cannot tell a row's originating topic, by looking in BigQuery table anymore. The partition number and the offset do match the originating topics though.

Hope the below screenshot helps to explain:
![image](https://user-images.githubusercontent.com/70140297/142616805-44cbc6ca-0d86-4df2-b064-fbb3a21290d9.png)

Is this an expected behaviour? Should the end result show the originating topic names instead, not just the "table name" in my example `KAFKA_METADATA.topic`, different from pre 2.0 version of the connector?

**Comment by C0urante** [comment]
This is an unfortunate reality of how the connector is implemented and limitations in the Kafka Connect API for handling situations like this.

[KIP-793](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=191336830) should make it possible to use an SMT that alters topic/partition/offset information with the connector and still get the original topic/partition/offset information included in the rows it writes to BigQuery when using the `kafkaDataFieldName` property.

Until then, if you would like to have the original (pre-transform) topic/partition/offset information for each record present in BigQuery while also using an SMT that alters records' topics/partitions/offsets, the connector's `kafkaDataFieldName` property should not be used, and instead, an SMT (such as [InsertField](https://docs.confluent.io/platform/current/connect/transforms/insertfield.html)) should be used to inject that metadata into record values before `RegexRouter` (or other, similar SMTs) have a chance to modify it.

Note that the behavior of `InsertField` will be slightly different from the behavior with the `kafkaDataFieldName` property, since the former will insert fields into the top-level value of the record, while the latter will insert them a single nested struct into the top-level value, which itself contains subfields for topic, partition, etc.
