### ISSUE TITLE
Publish configuration documentation

### ISSUE THREAD

**Issue by criccomini** [confluentinc/kafka-connect-bigquery#52]
When we migrated KCBQ over to the Confluent repo, the (out of date) wiki docs on the repo were left behind.

Does Confluent have any plans to publish the KCBQ docs on its website?

**Comment by C0urante** [comment]
We have some docs up: https://docs.confluent.io/current/connect/kafka-connect-bigquery/index.html

I've also reached out to our docs people and asked them to allow WePay to make contributions to our docs site; we're in the middle of some re-architecting on our docs site so that's frozen for the time but as soon as it's unblocked you guys should have access.

@criccomini For now, would you be willing to take a look at our docs site and see if it meets your standards? If it's good to go, we can link to it in the README on the project ASAP. Otherwise, I think we can migrate the wiki over here as a stopgap, include a deprecation notice letting people know that it won't be there forever, and work out any kinks with our docs.

**Comment by criccomini** [comment]
This is glorious. Exactly what I was looking for.

👏
