### ISSUE TITLE
Tasks fail for records containing values of connect Time data type

### ISSUE THREAD

**Issue by piter75** [confluentinc/kafka-connect-bigquery#65]
`TimeConverter` for [Time](https://github.com/apache/kafka/blob/2.5/connect/api/src/main/java/org/apache/kafka/connect/data/Time.java#L32) data type is currently missing in `KafkaLogicalConverters`.

This leads to kafka-connect-bigquery connector trying to insert `java.util.Date` object into `INTEGER` column which fails and stops the task.

```
Exception in thread "pool-4-thread-1" com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: table insertion failed for the following rows:
        [row index 0]: invalid: This field is not a record.
        [row index 1]: invalid: This field is not a record.
        at com.wepay.kafka.connect.bigquery.write.row.BigQueryWriter.writeRows(BigQueryWriter.java:131)
        at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:96)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by C0urante** [comment]
Thanks for bringing this to our attention, @piter75. Can you clarify whether the `INTEGER` column was created automatically by the connector? I suspect it was but would like to make sure.

As far as ways to address this go, we can either convert incoming logical time types into the number of milliseconds past midnight that they represent (using [built-in logic](https://github.com/apache/kafka/blob/afa5423356d3d2a2135a51200573b45d097f6d60/connect/api/src/main/java/org/apache/kafka/connect/data/Time.java#L52-L67) provided by Connect), or we can try to keep the `Date` objects as-are and change the DDL logic for table creation/schema updates to convert incoming logical time types into the BigQuery [`TIME` type](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#time_type).

If the connector has been creating tables with `INTEGER` type columns for logical time types, I think we'll have to default to the former approach so that the connector can work well with tables it's already created. This change could also be backported to prior branches and released as a bug fix.

We could then add support for the latter approach in the upcoming 2.0 release and enable it by default, allowing it to be toggled via configuration property so that users migrating from 1.6 (or before) can gracefully upgrade. This would be a backwards-incompatible change as it would cause the connector to break on existing datasets without reconfiguration by the user, but since 2.0 involves a major version bump, that's acceptable.

**Comment by piter75** [comment]
> Can you clarify whether the `INTEGER` column was created automatically by the connector? I suspect it was but would like to make sure.

Yes, `INTEGER` column was created by the connector based on the fact that the `Date` logical (connect) type is encoded with `Schema.INT32`.

> (...) change the DDL logic for table creation/schema updates to convert incoming logical time types into the BigQuery [`TIME` type](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#time_type).

I believe that ultimately the `TIME` column is the way to go forward and it is in line with [BigQuery's Avro conversions](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#logical_types) when logical types are enabled.

As for the backwards compatibility... in the current state of matters even if the connector creates `INTEGER` column in the BQ table it fails as soon as any record come that contains non empty value to be put in the column. It means that either no-one uses this `time-millis` logical type with `kafka-connect-bigquery` right now or they use it as nullable and always send nulls with it ;-)

But yeah, I understand the semantic versioning obligations so the two steps approach proposed by you is probably the most elegant one.

**Comment by C0urante** [comment]
> I believe that ultimately the TIME column is the way to go forward and it is in line with BigQuery's Avro conversions when logical types are enabled.

👍 

> As for the backwards compatibility... in the current state of matters even if the connector creates INTEGER column in the BQ table it fails as soon as any record come that contains non empty value to be put in the column. It means that either no-one uses this `time-millis` logical type with `kafka-connect-bigquery` right now or they use it as nullable and always send nulls with it ;-)

Yeah, I just want to protect against the case where the connector has permanently modified a table by adding an `INTEGER` column. If we advertise that we've "fixed" logical time types with the connector and then someone tries it out again against such a table, that'd (rightfully) cause some frustration. Keeping this in mind, we'd probably want to add a helpful message to the user (either via logs or exception) explaining why their connector is failing if it tries writing integer data to a `TIME` column or time data to an `INTEGER` column, and which config property to toggle to rectify things.


Cool, sounds like we have a game plan in mind for how to address this. cc @criccomini @mtagle @whynick1 @stoynov96 in case you guys want to weigh in 🙂 

@piter75 do you want to take this on? I probably won't have bandwidth to implement any time soon, but am happy to provide review if anyone files a PR.

**Comment by C0urante** [comment]
Added the `help wanted` label as there doesn't appear to be anyone willing to take this on for now.
