### ISSUE TITLE
Add partition expiration

### ISSUE THREAD

**Issue by philippama** [confluentinc/kafka-connect-bigquery#77]
GDPR requires us not to keep Personally Identifiable Information (PII) any longer than necessary. Therefore we need to be able to delete the data ingested from Kafka into BigQuery after a given amount of time. BigQuery offers partition expiration to help us do this. Could we have a new configuration option to be able to set partition expiration on the sink connector's destination table? We would be willing to contribute to add this feature.

**Comment by C0urante** [comment]
It looks like [table expiration](https://cloud.google.com/bigquery/docs/managing-tables#updating_a_tables_expiration_time) and [table partition expiration](https://cloud.google.com/bigquery/docs/managing-partitioned-tables#partition-expiration) can both be modified after table creation, which we should take into account here. I think this has two noteworthy implications:

- Today, it's possible to satisfy this use case by adding a step outside the connector workflow to modify the expiration time for tables that the connector creates. Not saying this is ideal, just noting this possibility as a workaround for users who need this right now or are unable to upgrade to a version of the connector that might have this feature at some later point. On top of this, BigQuery also supports dataset-level default expiration policies, which could also address some forms of this use case (although possibly with less granularity).
- We'd need to consider whether to apply new expiration policies when updating tables too (in addition to when creating them). I'm leaning towards only applying expiration policies when creating tables; otherwise, there's a risk of data loss if an expiration policy gets accidentally attached to an existing table.

With that out of the way, we should also consider whether we'd only want to support partition expiration, or also support global table expiration. And, with either option, what the new configuration properties we'd add to the connector would be (just their names and a brief summary of their behavior).

@philippama I think this is reasonable as long as none of the workarounds satisfy your use case. We should settle on a design here first; if/when that's complete, we can move on to a pull request.

**Comment by philippama** [comment]
We are keen to avoid a step outside the connector workflow in the long term if possible as this would either be a manual step or involve some extra task orchestration. We are already creating connectors using Terraform so that we have a repeatable process and an audit trail and would prefer to be able to add this functionality using the connector.

We would prefer to set partition expiration at a finer-grained level because we have found that the retention requirements for different PII are can be different and to apply the expiration at dataset level could lead to a proliferation of datasets.

We agree with you that only applying expiration policies when creating tables feels right. As you indicate, it is possible to update an existing table's partition expiration via the BigQuery API or even via the UI. An approach to applying partition expiration to an existing table could be to apply it manually but also to update the BigQuery Sink Connector configuration so that anyone wanting to create a new version of the connector would create it with the correct table options.

What would be the use case for table expiration? We are open to the idea but wonder whether it would be useful.

For the partition expiration, we could call the new property `partitionExpiration`  or `partitionExpirationMs`. The BigQuery api calls the field `expirationMs` and it lives within a `TimePartitioning` object. The behaviour description could be something like "The amount of time, in milliseconds, after which partitions should be deleted from the table."

**Comment by C0urante** [comment]
> We would prefer to set partition expiration at a finer-grained level because we have found that the retention requirements for different PII are can be different and to apply the expiration at dataset level could lead to a proliferation of datasets.

👍 , I'm convinced.

> We agree with you that only applying expiration policies when creating tables feels right.

🎉 

> What would be the use case for table expiration? We are open to the idea but wonder whether it would be useful.

The biggest use case I can think of right now is testing the connector, either internally (i.e., in integration tests) or externally (i.e., running a short-lived demo or proof of concept). It's a bit of a pain to have to always make sure that resources are cleaned up properly at the end of these, and there are always cases where things die unexpectedly and even if your test/demo automatically cleans things up after it's done, it may not reach that point.

I think we can decouple this from partition expiration for now if you'd prefer; if you'd like to implement both, great, if not, we can just focus on partition expiration for now.

`partitionExpirationMs` sounds good (lines up with the existing `batchLoadSec` and `mergeIntervalMs` properties). Description sounds fine.

I was going to ask about what the expected behavior should be when writing to an expired partition, which might happen if the connector is configured to target partitions based on the timestamps of Kafka records and it receives a record with a timestamp from a week, month, year, etc. ago. But after thinking about it some more it seems like that concern doesn't have to be tied to this feature, since it can arise regardless of whether the table's partition expiration policy was set by the connector or by some other user or application.

@philippama this sounds good to me, feel free to start implementing!

**Comment by philippama** [comment]
Thank you @C0urante !

> I was going to ask about what the expected behavior should be when writing to an expired partition, which might happen if the connector is configured to target partitions based on the timestamps of Kafka records and it receives a record with a timestamp from a week, month, year, etc. ago.

We experimented a bit with partition expiration directly in BigQuery, using SQL to create and populate a table and apply partition expiration at various times - on table creation, after table creation, before and after inserting data. We found that BigQuery behaved pretty nicely. For example:

- Creating a table with partition expiration then inserting data with a range of partition values -> only data with partition values later than the expiration period was stored.
- Creating a table and inserting data with a range of partition values then modifying the table to have partition expiration -> all data with partition values later than the expiration period was deleted.
- Modifying an existing table that had partition expiration to remove partition expiration -> all data subsequently inserted, whatever the partition value, was stored.

Therefore what happens when writing to an expired partition is, the data does not get written (or it is written and expires so quickly that we never see it).

Tagging @VermaSurbhi who is pairing with me.

**Comment by C0urante** [comment]
That sounds great! May warrant a small note about potential data loss in the docs for the config property but shouldn't be too worrisome as this is reasonable behavior when expiration is enabled.

**Comment by VermaSurbhi** [comment]
We looked into table expiration and we thought that it should be a separate issue. Table expiration is a timestamp (milliseconds since epoch) and you may wish to discuss whether you want to configure as a time or as a relative period, since your mentioned use-case is for test tables. It would also need a discussion about how timestamp field should be configured since there isn't any timestamp field already configured in connector.

**Comment by C0urante** [comment]
Addressed via https://github.com/confluentinc/kafka-connect-bigquery/pull/83
