### ISSUE TITLE
Its Upsert/Delete supported while enabling Batchload  

### ISSUE THREAD

**Issue by vigneshtvp** [confluentinc/kafka-connect-bigquery#93]
I am trying to do upsert by enabling batchload. only empty intermediate table is getting created, but no main table is creating.
want to check whether both upsert and batchload support simultaneously.

**Comment by C0urante** [comment]
Simultaneous GCS batch loading and upsert/delete are not supported at the moment, sorry!

**Comment by vigneshtvp** [comment]
Do you have any tentative timeline for this feature available?

**Comment by C0urante** [comment]
None at the moment, and I'm not even sure it'd make sense. Upsert/delete is implemented by writing to intermediate tables and then executing a `MERGE` query that draws data from them into the table the user sees. GCS batch loading is implemented by streaming into GCS instead of BigQuery and then periodically doing a batch load from GCS into BigQuery.

It's unclear whether the performance gains provided by GCS batch loading would be applicable for upsert/delete since data wouldn't be available to users after the initial load from GCS and would still have to go through that `MERGE` query before completing.
